server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          global cors:
            corsConfigurations:
              '[/**]':
#                allowedOrigins: "http://localhost:5173"
                allowedOriginPatterns: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: true


          routes:
#            - id: auth-service
#              uri: lb://auth-service
#              predicates:
#                - Path=/api/auth/**

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
                - Path=/api/auth/**

            - id: book-service
              uri: lb://book-service
              predicates:
                - Path=/api/books/**, /api/authors/**, /api/categories/**, /api/publishers/**, /api/receipts/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/