server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/bookweb_user?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: n20dccn037@student.ptithcm.edu.vn
    password: wuqy wehr waja tghu
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  secret: my_super_secret_key_at_least_256_bits
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}


google:
  client:
    id: 124223479536-3bn4fvk4us52otg229jqq0etjp296s5s.apps.googleusercontent.com
    secret: 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
  redirect:
    uri: http://localhost:3000/authenticate
